import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E94C3D",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#E94C3D",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  content: {
    flex: 1,
    backgroundColor: "#f2f2f2",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
  },
  section: {
    marginVertical: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  destinationItem: {
    width: 200,
    borderRadius: 12,
    marginRight: 12,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 0,
  },
  destinationImageContainer: {
    height: 120,
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: "#E94C3D",
  },
  destinationName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  destinationInfoContainer: {
    padding: 12,
  },
  destinationLocation: {
    fontSize: 14,
    color: "#666",
  },
  destinationClimate: {
    fontSize: 14,
    color: "#999",
  },
  flightItem: {
    width: 200,
    borderRadius: 12,
    marginRight: 12,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
  flightInfoContainer: {
    flex: 1,
  },
  flightNumber: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  flightRoute: {
    fontSize: 14,
    color: "#666",
  },
  flightPriceContainer: {
    alignItems: "flex-end",
  },
  flightPrice: {
    fontSize: 14,
    color: "#333",
  },
  accommodationItem: {
    width: 200,
    borderRadius: 12,
    marginRight: 12,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 0,
  },
  accommodationImageContainer: {
    height: 120,
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    backgroundColor: "#E94C3D",
  },
  accommodationName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  accommodationInfoContainer: {
    padding: 12,
  },
  accommodationType: {
    fontSize: 14,
    color: "#666666",
  },
  accommodationAddress: {
    fontSize: 14,
    color: "#999",
  },
  accommodationRating: {
    fontSize: 14,
    color: "#333",
  },
  accommodationPrice: {
    fontSize: 14,
    color: "#333",
  },
  activityItem: {
    width: 200,
    borderRadius: 12,
    marginRight: 12,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 0,
    padding: 12,
  },
  activityInfoContainer: {
    flex: 1,
  },
  activityName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  activityDescription: {
    fontSize: 14,
    color: "#666",
  },
  activityLocation: {
    fontSize: 14,
    color: "#999",
  },
  activityDuration: {
    fontSize: 14,
    color: "#333",
  },
  activityPrice: {
    fontSize: 14,
    color: "#333",
  },
  floatingButton: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#E94C3D",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  floatingButtonText: {
    fontSize: 32,
    color: "#fff",
    fontWeight: "bold",
  },
  emptyText: {
    fontSize: 16,
    color: "#666",
    textAlign: "left",
    marginVertical: 16,
  },
  loader: {
    marginTop: 20,
  },
});
